name: "Preview environment garbage collection"
on:
    workflow_dispatch:
jobs:
    gc:
        name: "Delete unused preview environments"
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v3
            - name: Garbage collect
              env:
                  HOME: /home/gitpod
                  PREVIEW_ENV_DEV_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
                  PREVIEW_ENV_DEV_SA_KEY_PATH: "/home/gitpod/.config/gcloud/preview-environment-dev-sa.json"
              run: |
                  echo "${PREVIEW_ENV_DEV_SA_KEY}" > "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
                  gcloud auth activate-service-account --key-file "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
                  leeway run dev/preview/previewctl:install
                  previewctl get-credentials --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
                  previewctl list stale
