name: "Preview environment garbage collection"
on:
    workflow_dispatch:
jobs:
    stale:
        name: "Find stale preview environments"
        runs-on: [self-hosted]
        container:
            image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:mads-leeway-v0.7.3.4
        outputs:
            names: ${{ steps.set-matrix.outputs.names }}
        steps:
            - uses: actions/checkout@v3
            - name: Compute matrix
              id: set-matrix
              env:
                  HOME: /home/gitpod
                  PREVIEW_ENV_DEV_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
                  PREVIEW_ENV_DEV_SA_KEY_PATH: "/home/gitpod/.config/gcloud/preview-environment-dev-sa.json"
                  # Used by 'previewctl list stale'
                  GOOGLE_APPLICATION_CREDENTIALS: "/home/gitpod/.config/gcloud/preview-environment-dev-sa.json"
              shell: bash
              run: |
                  set -euo pipefail

                  echo "${PREVIEW_ENV_DEV_SA_KEY}" > "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
                  gcloud auth activate-service-account --key-file "${PREVIEW_ENV_DEV_SA_KEY_PATH}"

                  export LEEWAY_WORKSPACE_ROOT="$(pwd)"
                  leeway run dev/preview/previewctl:install

                  previewctl get-credentials --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
                  previewctl list stale | jq --null-input --raw-input --compact-output '[inputs | select(length>0)]' > /tmp/stale-json
                  echo "names=$(cat /tmp/stale-json)" >> $GITHUB_OUTPUT

    delete:
        name: "Delete preview environment"
        needs: [stale]
        runs-on: [self-hosted]
        strategy:
            matrix:
                name: ${{ fromJSON(needs.stale.outputs.names) }}
        steps:
            - uses: actions/checkout@v3
            - name: Delete preview environment ${{ matrix.name }}
              run: echo ${{ matrix.name }}
            # - name: Delete preview environment ${{ matrix.name }}
            #   uses: ./.github/actions/delete-preview
            #   with:
            #       name: ${{ matrix.name }}
            #       sa_key: ${{ secrets.GCP_CREDENTIALS }}
